//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyTechAudit.PowerAccounting.ReportSupport {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DictionariesValueResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DictionariesValueResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnergyTechAudit.PowerAccounting.ReportSupport.DictionariesValueResources", typeof(DictionariesValueResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KM5.
        /// </summary>
        public static string DeviceCodeKm5 {
            get {
                return ResourceManager.GetString("DeviceCodeKm5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM5.
        /// </summary>
        public static string DeviceCodeRm5 {
            get {
                return ResourceManager.GetString("DeviceCodeRm5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV7.
        /// </summary>
        public static string DeviceCodeTv7 {
            get {
                return ResourceManager.GetString("DeviceCodeTv7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string PeriodTypeCodeDay {
            get {
                return ResourceManager.GetString("PeriodTypeCodeDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string PeriodTypeCodeHour {
            get {
                return ResourceManager.GetString("PeriodTypeCodeHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem104_Tesmart.
        /// </summary>
        public static string Tem104_TesmartDeviceCode {
            get {
                return ResourceManager.GetString("Tem104_TesmartDeviceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem104.
        /// </summary>
        public static string Tem104DeviceCode {
            get {
                return ResourceManager.GetString("Tem104DeviceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem106.
        /// </summary>
        public static string Tem106DeviceCode {
            get {
                return ResourceManager.GetString("Tem106DeviceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem116.
        /// </summary>
        public static string Tem116DeviceCode {
            get {
                return ResourceManager.GetString("Tem116DeviceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tesma106.
        /// </summary>
        public static string Tesma106DeviceCode {
            get {
                return ResourceManager.GetString("Tesma106DeviceCode", resourceCulture);
            }
        }
    }
}
