//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyTechAudit.PowerAccounting.ReportSupport {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FieldsNamesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FieldsNamesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnergyTechAudit.PowerAccounting.ReportSupport.FieldsNamesResources", typeof(FieldsNamesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cws.Pressure.SupplyPipe.
        /// </summary>
        public static string CwsPressureSupplyPipe {
            get {
                return ResourceManager.GetString("CwsPressureSupplyPipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cws.Pressure.SupplyPipe.Next.
        /// </summary>
        public static string CwsPressureSupplyPipeNext {
            get {
                return ResourceManager.GetString("CwsPressureSupplyPipeNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cws.Time.Normal.Daily.
        /// </summary>
        public static string CwsTimeNormalDailyFieldName {
            get {
                return ResourceManager.GetString("CwsTimeNormalDailyFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cws.Time.Normal.Last.Daily.
        /// </summary>
        public static string CwsTimeNormalLastDailyFieldName {
            get {
                return ResourceManager.GetString("CwsTimeNormalLastDailyFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cws.Volume.Daily.
        /// </summary>
        public static string CwsVolumeDailyFieldName {
            get {
                return ResourceManager.GetString("CwsVolumeDailyFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cws.Volume.Diff.
        /// </summary>
        public static string CwsVolumeDiffFieldName {
            get {
                return ResourceManager.GetString("CwsVolumeDiffFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cws.Volume.Diff.Next.
        /// </summary>
        public static string CwsVolumeDiffNextFieldName {
            get {
                return ResourceManager.GetString("CwsVolumeDiffNextFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cws.Volume.
        /// </summary>
        public static string CwsVolumeFieldName {
            get {
                return ResourceManager.GetString("CwsVolumeFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cws.Volume.Last.Daily.
        /// </summary>
        public static string CwsVolumeLastDailyFieldName {
            get {
                return ResourceManager.GetString("CwsVolumeLastDailyFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cws.Volume.Next.
        /// </summary>
        public static string CwsVolumeNextFieldName {
            get {
                return ResourceManager.GetString("CwsVolumeNextFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cws.Volume.Pipe2.Diff.
        /// </summary>
        public static string CwsVolumePipe2DiffFieldName {
            get {
                return ResourceManager.GetString("CwsVolumePipe2DiffFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cws.Volume.Pipe2.Diff.Next.
        /// </summary>
        public static string CwsVolumePipe2DiffNextFieldName {
            get {
                return ResourceManager.GetString("CwsVolumePipe2DiffNextFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cws.Volume.Pipe2.
        /// </summary>
        public static string CwsVolumePipe2FieldName {
            get {
                return ResourceManager.GetString("CwsVolumePipe2FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cws.Volume.Pipe2.Next.
        /// </summary>
        public static string CwsVolumePipe2NextFieldName {
            get {
                return ResourceManager.GetString("CwsVolumePipe2NextFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ElectroSys.ActivePower.Minus.Diff.
        /// </summary>
        public static string ElectroSysActivePowerMinusDiffFieldName {
            get {
                return ResourceManager.GetString("ElectroSysActivePowerMinusDiffFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ElectroSys.ActivePower.Plus.Diff.
        /// </summary>
        public static string ElectroSysActivePowerPlusDiffFieldName {
            get {
                return ResourceManager.GetString("ElectroSysActivePowerPlusDiffFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ElectroSys.ActivePower.Plus.Sum.
        /// </summary>
        public static string ElectroSysActivePowerPlusSumFieldName {
            get {
                return ResourceManager.GetString("ElectroSysActivePowerPlusSumFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ElectroSys.ErrorInfo.
        /// </summary>
        public static string ElectroSysErrorInfoFieldName {
            get {
                return ResourceManager.GetString("ElectroSysErrorInfoFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ElectroSys.ReactivePower.Minus.Diff.
        /// </summary>
        public static string ElectroSysReactivePowerMinusDiffFieldName {
            get {
                return ResourceManager.GetString("ElectroSysReactivePowerMinusDiffFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ElectroSys.ReactivePower.Plus.Diff.
        /// </summary>
        public static string ElectroSysReactivePowerPlusDiffFieldName {
            get {
                return ResourceManager.GetString("ElectroSysReactivePowerPlusDiffFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ElectroSys.Time.Normal.
        /// </summary>
        public static string ElectroSysTimeNormalFieldName {
            get {
                return ResourceManager.GetString("ElectroSysTimeNormalFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ElectroSys.Time.Normal.Next.
        /// </summary>
        public static string ElectroSysTimeNormalNextFieldName {
            get {
                return ResourceManager.GetString("ElectroSysTimeNormalNextFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas.Correction.
        /// </summary>
        public static string GasCorrectionFieldName {
            get {
                return ResourceManager.GetString("GasCorrectionFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas.ErrorInfo.
        /// </summary>
        public static string GasErrorInfoFieldName {
            get {
                return ResourceManager.GetString("GasErrorInfoFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas.Pressure.
        /// </summary>
        public static string GasPressureFieldName {
            get {
                return ResourceManager.GetString("GasPressureFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas.Temperature.
        /// </summary>
        public static string GasTemperatureFieldName {
            get {
                return ResourceManager.GetString("GasTemperatureFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas.Time.Denial.Diff.
        /// </summary>
        public static string GasTimeDenialDiffFieldName {
            get {
                return ResourceManager.GetString("GasTimeDenialDiffFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas.Time.Normal.Diff.
        /// </summary>
        public static string GasTimeNormalDiffFieldName {
            get {
                return ResourceManager.GetString("GasTimeNormalDiffFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas.Time.Normal.
        /// </summary>
        public static string GasTimeNormalFieldName {
            get {
                return ResourceManager.GetString("GasTimeNormalFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas.Volume.Standard.Diff.
        /// </summary>
        public static string GasVolumeStandardDiffFieldName {
            get {
                return ResourceManager.GetString("GasVolumeStandardDiffFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas.Volume.Standard.
        /// </summary>
        public static string GasVolumeStandardFieldName {
            get {
                return ResourceManager.GetString("GasVolumeStandardFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas.Volume.Work.Diff.
        /// </summary>
        public static string GasVolumeWorkDiffFieldName {
            get {
                return ResourceManager.GetString("GasVolumeWorkDiffFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas.Volume.Work.
        /// </summary>
        public static string GasVolumeWorkFieldName {
            get {
                return ResourceManager.GetString("GasVolumeWorkFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HeatSys.Heat.Total.Daily.
        /// </summary>
        public static string HeatSysHeatTotalDailyFieldName {
            get {
                return ResourceManager.GetString("HeatSysHeatTotalDailyFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HeatSys.Heat.Total.Diff.
        /// </summary>
        public static string HeatSysHeatTotalDiffFieldName {
            get {
                return ResourceManager.GetString("HeatSysHeatTotalDiffFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HeatSys.Heat.Total.Last.Daily.
        /// </summary>
        public static string HeatSysHeatTotalLastDailyFieldName {
            get {
                return ResourceManager.GetString("HeatSysHeatTotalLastDailyFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HeatSys.Mass.ReturnPipe.Daily.
        /// </summary>
        public static string HeatSysMassReturnPipeDailyFieldName {
            get {
                return ResourceManager.GetString("HeatSysMassReturnPipeDailyFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HeatSys.Mass.ReturnPipe.Last.Daily.
        /// </summary>
        public static string HeatSysMassReturnPipeLastDailyFieldName {
            get {
                return ResourceManager.GetString("HeatSysMassReturnPipeLastDailyFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HeatSys.Mass.SupplyPipe.Daily.
        /// </summary>
        public static string HeatSysMassSupplyPipeDailyFieldName {
            get {
                return ResourceManager.GetString("HeatSysMassSupplyPipeDailyFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HeatSys.Mass.SupplyPipe.Last.Daily.
        /// </summary>
        public static string HeatSysMassSupplyPipeLastDailyFieldName {
            get {
                return ResourceManager.GetString("HeatSysMassSupplyPipeLastDailyFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HeatSys.Pressure.SupplyPipe.
        /// </summary>
        public static string HeatSysPressureSupplyPipe {
            get {
                return ResourceManager.GetString("HeatSysPressureSupplyPipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HeatSys.Temper.ReturnPipe.
        /// </summary>
        public static string HeatSysTemperReturnPipeFieldName {
            get {
                return ResourceManager.GetString("HeatSysTemperReturnPipeFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HeatSys.Temper.SupplyPipe.
        /// </summary>
        public static string HeatSysTemperSupplyPipeFieldName {
            get {
                return ResourceManager.GetString("HeatSysTemperSupplyPipeFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HeatSys.Time.Normal.Daily.
        /// </summary>
        public static string HeatSysTimeNormalDailyFieldName {
            get {
                return ResourceManager.GetString("HeatSysTimeNormalDailyFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HeatSys.Time.Normal.Last.Daily.
        /// </summary>
        public static string HeatSysTimeNormalLastDailyFieldName {
            get {
                return ResourceManager.GetString("HeatSysTimeNormalLastDailyFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hws.Heat.Total.Daily.
        /// </summary>
        public static string HwsHeatTotalDailyFieldName {
            get {
                return ResourceManager.GetString("HwsHeatTotalDailyFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hws.Heat.Total.Diff.
        /// </summary>
        public static string HwsHeatTotalDiffFieldName {
            get {
                return ResourceManager.GetString("HwsHeatTotalDiffFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hws.Heat.Total.Last.Daily.
        /// </summary>
        public static string HwsHeatTotalLastDailyFieldName {
            get {
                return ResourceManager.GetString("HwsHeatTotalLastDailyFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hws.Mass.ReturnPipe.Daily.
        /// </summary>
        public static string HwsMassReturnPipeDailyFieldName {
            get {
                return ResourceManager.GetString("HwsMassReturnPipeDailyFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hws.Mass.ReturnPipe.Last.Daily.
        /// </summary>
        public static string HwsMassReturnPipeLastDailyFieldName {
            get {
                return ResourceManager.GetString("HwsMassReturnPipeLastDailyFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hws.Mass.SupplyPipe.Daily.
        /// </summary>
        public static string HwsMassSupplyPipeDailyFieldName {
            get {
                return ResourceManager.GetString("HwsMassSupplyPipeDailyFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hws.Mass.SupplyPipe.Last.Daily.
        /// </summary>
        public static string HwsMassSupplyPipeLastDailyFieldName {
            get {
                return ResourceManager.GetString("HwsMassSupplyPipeLastDailyFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hws.Time.Normal.Daily.
        /// </summary>
        public static string HwsTimeNormalDailyFieldName {
            get {
                return ResourceManager.GetString("HwsTimeNormalDailyFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hws.Time.Normal.Last.Daily.
        /// </summary>
        public static string HwsTimeNormalLastDailyFieldName {
            get {
                return ResourceManager.GetString("HwsTimeNormalLastDailyFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.Normal.
        /// </summary>
        public static string TimeNormalFieldName {
            get {
                return ResourceManager.GetString("TimeNormalFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeString.
        /// </summary>
        public static string TimeStringFieldName {
            get {
                return ResourceManager.GetString("TimeStringFieldName", resourceCulture);
            }
        }
    }
}
