//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyTechAudit.PowerAccounting.ReportSupport {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReportInternalColumnNameResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportInternalColumnNameResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnergyTechAudit.PowerAccounting.ReportSupport.ReportInternalColumnNameResources", typeof(ReportInternalColumnNameResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V0_1.
        /// </summary>
        public static string V0_1 {
            get {
                return ResourceManager.GetString("V0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V1_2.
        /// </summary>
        public static string V1_2 {
            get {
                return ResourceManager.GetString("V1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V10_11.
        /// </summary>
        public static string V10_11 {
            get {
                return ResourceManager.GetString("V10_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V11_12.
        /// </summary>
        public static string V11_12 {
            get {
                return ResourceManager.GetString("V11_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V12_13.
        /// </summary>
        public static string V12_13 {
            get {
                return ResourceManager.GetString("V12_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V13_14.
        /// </summary>
        public static string V13_14 {
            get {
                return ResourceManager.GetString("V13_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V14_15.
        /// </summary>
        public static string V14_15 {
            get {
                return ResourceManager.GetString("V14_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V15_16.
        /// </summary>
        public static string V15_16 {
            get {
                return ResourceManager.GetString("V15_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V16_17.
        /// </summary>
        public static string V16_17 {
            get {
                return ResourceManager.GetString("V16_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V17_18.
        /// </summary>
        public static string V17_18 {
            get {
                return ResourceManager.GetString("V17_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V18_19.
        /// </summary>
        public static string V18_19 {
            get {
                return ResourceManager.GetString("V18_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V19_20.
        /// </summary>
        public static string V19_20 {
            get {
                return ResourceManager.GetString("V19_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V2_3.
        /// </summary>
        public static string V2_3 {
            get {
                return ResourceManager.GetString("V2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V20_21.
        /// </summary>
        public static string V20_21 {
            get {
                return ResourceManager.GetString("V20_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V21_22.
        /// </summary>
        public static string V21_22 {
            get {
                return ResourceManager.GetString("V21_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V22_23.
        /// </summary>
        public static string V22_23 {
            get {
                return ResourceManager.GetString("V22_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V23_0.
        /// </summary>
        public static string V23_0 {
            get {
                return ResourceManager.GetString("V23_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V3_4.
        /// </summary>
        public static string V3_4 {
            get {
                return ResourceManager.GetString("V3_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V4_5.
        /// </summary>
        public static string V4_5 {
            get {
                return ResourceManager.GetString("V4_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V5_6.
        /// </summary>
        public static string V5_6 {
            get {
                return ResourceManager.GetString("V5_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V6_7.
        /// </summary>
        public static string V6_7 {
            get {
                return ResourceManager.GetString("V6_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V7_8.
        /// </summary>
        public static string V7_8 {
            get {
                return ResourceManager.GetString("V7_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V8_9.
        /// </summary>
        public static string V8_9 {
            get {
                return ResourceManager.GetString("V8_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V9_10.
        /// </summary>
        public static string V9_10 {
            get {
                return ResourceManager.GetString("V9_10", resourceCulture);
            }
        }
    }
}
