//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyTechAudit.PowerAccounting.ReportSupport {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReportPluginResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportPluginResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnergyTechAudit.PowerAccounting.ReportSupport.ReportPluginResources", typeof(ReportPluginResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActiveAverage.
        /// </summary>
        public static string ActiveAverage {
            get {
                return ResourceManager.GetString("ActiveAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActiveKz.
        /// </summary>
        public static string ActiveKz {
            get {
                return ResourceManager.GetString("ActiveKz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActiveMax.
        /// </summary>
        public static string ActiveMax {
            get {
                return ResourceManager.GetString("ActiveMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActivePowerSecondData.
        /// </summary>
        public static string ActivePowerSecondData {
            get {
                return ResourceManager.GetString("ActivePowerSecondData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActivePowerSummaryData.
        /// </summary>
        public static string ActivePowerSummaryData {
            get {
                return ResourceManager.GetString("ActivePowerSummaryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActiveSum.
        /// </summary>
        public static string ActiveSum {
            get {
                return ResourceManager.GetString("ActiveSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-.
        /// </summary>
        public static string AMinus {
            get {
                return ResourceManager.GetString("AMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A+.
        /// </summary>
        public static string APlus {
            get {
                return ResourceManager.GetString("APlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXEC [Programmability].[CalculateVkt7IntegratorAfterFinalDate] @MeasurementDeviceId, @PeriodTypeId, @DiffParameterId, @SumParameterId, @Date, @FinalDate.
        /// </summary>
        public static string CalculateVkt7IntegratorAfterFinalDate {
            get {
                return ResourceManager.GetString("CalculateVkt7IntegratorAfterFinalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChannelId.
        /// </summary>
        public static string ChannelId {
            get {
                return ResourceManager.GetString("ChannelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {channelId}.
        /// </summary>
        public static string ChannelIdSubs {
            get {
                return ResourceManager.GetString("ChannelIdSubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        public static string CommaDelimiter {
            get {
                return ResourceManager.GetString("CommaDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cws.
        /// </summary>
        public static string CwsResourceSystemTypeCode {
            get {
                return ResourceManager.GetString("CwsResourceSystemTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string DashSymbol {
            get {
                return ResourceManager.GetString("DashSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Date.
        /// </summary>
        public static string DateSqlParameter {
            get {
                return ResourceManager.GetString("DateSqlParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DesignFactor.
        /// </summary>
        public static string DesignFactor {
            get {
                return ResourceManager.GetString("DesignFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diff.
        /// </summary>
        public static string Diff {
            get {
                return ResourceManager.GetString("Diff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @DiffParameterId.
        /// </summary>
        public static string DiffParameterIdSqlParameter {
            get {
                return ResourceManager.GetString("DiffParameterIdSqlParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string DotSymbol {
            get {
                return ResourceManager.GetString("DotSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorInfo.
        /// </summary>
        public static string ErrorInfo {
            get {
                return ResourceManager.GetString("ErrorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @FinalDate.
        /// </summary>
        public static string FinalDateSqlParameter {
            get {
                return ResourceManager.GetString("FinalDateSqlParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat.
        /// </summary>
        public static string Heat {
            get {
                return ResourceManager.GetString("Heat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  тепл. энергии.
        /// </summary>
        public static string HeatEnergy {
            get {
                return ResourceManager.GetString("HeatEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HeatSysMakeup.
        /// </summary>
        public static string HeatSysMakeupResourceSubsystemTypeCode {
            get {
                return ResourceManager.GetString("HeatSysMakeupResourceSubsystemTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HeatSys.
        /// </summary>
        public static string HeatSysResourceSystemTypeCode {
            get {
                return ResourceManager.GetString("HeatSysResourceSystemTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hws.
        /// </summary>
        public static string HwsResourceSystemTypeCode {
            get {
                return ResourceManager.GetString("HwsResourceSystemTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to includePeriodEnd = 0.
        /// </summary>
        public static string IncludePeriodEndEqual0 {
            get {
                return ResourceManager.GetString("IncludePeriodEndEqual0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to includePeriodEnd = 1.
        /// </summary>
        public static string IncludePeriodEndEqual1 {
            get {
                return ResourceManager.GetString("IncludePeriodEndEqual1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {includePeriodEnd}.
        /// </summary>
        public static string IncludePeriodEndSubs {
            get {
                return ResourceManager.GetString("IncludePeriodEndSubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IntegrableValue.
        /// </summary>
        public static string IntegrableValue {
            get {
                return ResourceManager.GetString("IntegrableValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IntegrableValue = false.
        /// </summary>
        public static string IntegrableValueFalse {
            get {
                return ResourceManager.GetString("IntegrableValueFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IntegrableValue = true.
        /// </summary>
        public static string IntegrableValueTrue {
            get {
                return ResourceManager.GetString("IntegrableValueTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string IntToBooleanTrue {
            get {
                return ResourceManager.GetString("IntToBooleanTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Период G&lt;min.
        /// </summary>
        public static string Km5ErrorsPlugin_gInfo {
            get {
                return ResourceManager.GetString("Km5ErrorsPlugin_gInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g.
        /// </summary>
        public static string Km5ErrorsPlugin_gType {
            get {
                return ResourceManager.GetString("Km5ErrorsPlugin_gType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Период t2-t1 &lt; min.
        /// </summary>
        public static string Km5ErrorsPluginDInfo {
            get {
                return ResourceManager.GetString("Km5ErrorsPluginDInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        public static string Km5ErrorsPluginDType {
            get {
                return ResourceManager.GetString("Km5ErrorsPluginDType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Период функц. отказа.
        /// </summary>
        public static string Km5ErrorsPluginEInfo {
            get {
                return ResourceManager.GetString("Km5ErrorsPluginEInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string Km5ErrorsPluginEType {
            get {
                return ResourceManager.GetString("Km5ErrorsPluginEType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Период G&gt;max.
        /// </summary>
        public static string Km5ErrorsPluginGInfo {
            get {
                return ResourceManager.GetString("Km5ErrorsPluginGInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.
        /// </summary>
        public static string Km5ErrorsPluginGType {
            get {
                return ResourceManager.GetString("Km5ErrorsPluginGType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsValidRowState = false.
        /// </summary>
        public static string Km5ErrorsPluginPowerFailureDaysCondition {
            get {
                return ResourceManager.GetString("Km5ErrorsPluginPowerFailureDaysCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Период отключения питания.
        /// </summary>
        public static string Km5ErrorsPluginUInfo {
            get {
                return ResourceManager.GetString("Km5ErrorsPluginUInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U.
        /// </summary>
        public static string Km5ErrorsPluginUType {
            get {
                return ResourceManager.GetString("Km5ErrorsPluginUType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass.
        /// </summary>
        public static string Mass {
            get {
                return ResourceManager.GetString("Mass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxHour.
        /// </summary>
        public static string MaxHour {
            get {
                return ResourceManager.GetString("MaxHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxHoursRange.
        /// </summary>
        public static string MaxHoursRange {
            get {
                return ResourceManager.GetString("MaxHoursRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MeasurementDeviceId.
        /// </summary>
        public static string MeasurementDeviceSqlParameter {
            get {
                return ResourceManager.GetString("MeasurementDeviceSqlParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string OneDigit {
            get {
                return ResourceManager.GetString("OneDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {periodBegin}.
        /// </summary>
        public static string PeriodBeginSubs {
            get {
                return ResourceManager.GetString("PeriodBeginSubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {periodEnd}.
        /// </summary>
        public static string PeriodEndSubs {
            get {
                return ResourceManager.GetString("PeriodEndSubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to periodTypeId = 2.
        /// </summary>
        public static string PeriodTypeIdEqual2 {
            get {
                return ResourceManager.GetString("PeriodTypeIdEqual2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to periodTypeId = 3.
        /// </summary>
        public static string PeriodTypeIdEqual3 {
            get {
                return ResourceManager.GetString("PeriodTypeIdEqual3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @PeriodTypeId.
        /// </summary>
        public static string PeriodTypeIdSqlParameter {
            get {
                return ResourceManager.GetString("PeriodTypeIdSqlParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {periodTypeId}.
        /// </summary>
        public static string PeriodTypeIdSubs {
            get {
                return ResourceManager.GetString("PeriodTypeIdSubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrecisionChannel1.
        /// </summary>
        public static string PrecisionChannel1 {
            get {
                return ResourceManager.GetString("PrecisionChannel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrecisionChannel2.
        /// </summary>
        public static string PrecisionChannel2 {
            get {
                return ResourceManager.GetString("PrecisionChannel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrecisionHeat.
        /// </summary>
        public static string PrecisionHeat {
            get {
                return ResourceManager.GetString("PrecisionHeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReactivePowerFirstData.
        /// </summary>
        public static string ReactivePowerFirstData {
            get {
                return ResourceManager.GetString("ReactivePowerFirstData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReactivePowerSecondData.
        /// </summary>
        public static string ReactivePowerSecondData {
            get {
                return ResourceManager.GetString("ReactivePowerSecondData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReturnPipe.
        /// </summary>
        public static string ReturnPipe {
            get {
                return ResourceManager.GetString("ReturnPipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R-.
        /// </summary>
        public static string RMinus {
            get {
                return ResourceManager.GetString("RMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R+.
        /// </summary>
        public static string RPlus {
            get {
                return ResourceManager.GetString("RPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сточные воды (V1-V2).
        /// </summary>
        public static string SewageV1V2Description {
            get {
                return ResourceManager.GetString("SewageV1V2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StringValue.
        /// </summary>
        public static string StringValue {
            get {
                return ResourceManager.GetString("StringValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @SumParameterId.
        /// </summary>
        public static string SumParameterIdSqlParameter {
            get {
                return ResourceManager.GetString("SumParameterIdSqlParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplyPipe.
        /// </summary>
        public static string SupplyPipe {
            get {
                return ResourceManager.GetString("SupplyPipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---.
        /// </summary>
        public static string TripleHyphen {
            get {
                return ResourceManager.GetString("TripleHyphen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string TwoDigit {
            get {
                return ResourceManager.GetString("TwoDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {userName}.
        /// </summary>
        public static string UserNameSubs {
            get {
                return ResourceManager.GetString("UserNameSubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string WhiteSpace {
            get {
                return ResourceManager.GetString("WhiteSpace", resourceCulture);
            }
        }
    }
}
