//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyTechAudit.PowerAccounting.ReportSupport {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringFormatResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringFormatResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnergyTechAudit.PowerAccounting.ReportSupport.StringFormatResources", typeof(StringFormatResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active{0}_{1}.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ASC.
        /// </summary>
        public static string ASC {
            get {
                return ResourceManager.GetString("ASC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVG([{0}]).
        /// </summary>
        public static string Avg {
            get {
                return ResourceManager.GetString("Avg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXEC [Programmability].[GetAllDeviceTechnicalParameters] @measurementDeviceId={0}.
        /// </summary>
        public static string CallGetAllDeviceTechnicalParametersSP {
            get {
                return ResourceManager.GetString("CallGetAllDeviceTechnicalParametersSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel{0}.
        /// </summary>
        public static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:D4}{1:D2}{2:D2} {3:D2}:{4:D2}:{5:D2}.
        /// </summary>
        public static string DateStringInSqlStyle {
            get {
                return ResourceManager.GetString("DateStringInSqlStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} DESC.
        /// </summary>
        public static string DESC {
            get {
                return ResourceManager.GetString("DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.Diff.
        /// </summary>
        public static string DiffParameter {
            get {
                return ResourceManager.GetString("DiffParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.EmergencyParameter.
        /// </summary>
        public static string EmergencyParameterColumn {
            get {
                return ResourceManager.GetString("EmergencyParameterColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.ErrorInfo.
        /// </summary>
        public static string ErrorInfoColumn {
            get {
                return ResourceManager.GetString("ErrorInfoColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.Heat.Total.
        /// </summary>
        public static string HeatTotal {
            get {
                return ResourceManager.GetString("HeatTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.Heat.Total.Diff.
        /// </summary>
        public static string HeatTotalDiff {
            get {
                return ResourceManager.GetString("HeatTotalDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.Heat.Total.Next.
        /// </summary>
        public static string HeatTotalNext {
            get {
                return ResourceManager.GetString("HeatTotalNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:d2}:{1:d2}:{2:d2} (час:мин:сек).
        /// </summary>
        public static string HourMinuteSecondFormat {
            get {
                return ResourceManager.GetString("HourMinuteSecondFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:00}.{1:00}-{2:00}.{3:00}.
        /// </summary>
        public static string IrvisDayTimeString {
            get {
                return ResourceManager.GetString("IrvisDayTimeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:00}.{1:00} {2:00}:00-{3:00}.{4:00} {5:00}:00.
        /// </summary>
        public static string IrvisHourTimeString {
            get {
                return ResourceManager.GetString("IrvisHourTimeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsValidRowState = true and {0}.Time.Normal.Diff is not null and {0}.Time.Normal.Diff &lt; 24.
        /// </summary>
        public static string Km5ErrorsPluginErrorDaysCondition {
            get {
                return ResourceManager.GetString("Km5ErrorsPluginErrorDaysCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time &gt; &apos;{0:o}&apos; and Time &lt; &apos;{1:o}&apos;.
        /// </summary>
        public static string Km5ErrorsPluginErrorsCondition {
            get {
                return ResourceManager.GetString("Km5ErrorsPluginErrorsCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0, -25} (U) {1, -40}{2}{3, -25} (E) {4, -40}{5}{6,-25} (D) {7, -40}{8}{9, -25} (g) {10, -40}{11}{12, -25} (G) {13, -40}.
        /// </summary>
        public static string Km5ErrorsResultInfoString {
            get {
                return ResourceManager.GetString("Km5ErrorsResultInfoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} мин.
        /// </summary>
        public static string MinuteFormat {
            get {
                return ResourceManager.GetString("MinuteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время работы прибора после сброса {0} ч{1}.
        /// </summary>
        public static string PeriodAfterReset {
            get {
                return ResourceManager.GetString("PeriodAfterReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to periodBegin = &apos;{0}&apos;.
        /// </summary>
        public static string PeriodBeginSql {
            get {
                return ResourceManager.GetString("PeriodBeginSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to periodEnd = &apos;{0}&apos;.
        /// </summary>
        public static string PeriodEndSql {
            get {
                return ResourceManager.GetString("PeriodEndSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactive{0}_{1}.
        /// </summary>
        public static string Reactive {
            get {
                return ResourceManager.GetString("Reactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} = &apos;{0:o}&apos;.
        /// </summary>
        public static string SelectByTimeColumnCondition {
            get {
                return ResourceManager.GetString("SelectByTimeColumnCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time = &apos;{0:o}&apos;.
        /// </summary>
        public static string SelectByTimeColumnCondition2 {
            get {
                return ResourceManager.GetString("SelectByTimeColumnCondition2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.Time.Denial.
        /// </summary>
        public static string TimeDenial {
            get {
                return ResourceManager.GetString("TimeDenial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.Time.Denial.Diff.
        /// </summary>
        public static string TimeDenialDiff {
            get {
                return ResourceManager.GetString("TimeDenialDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Период отсутст. счета{0} {1} ч{2}.
        /// </summary>
        public static string TimeDenialPeriod {
            get {
                return ResourceManager.GetString("TimeDenialPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.Time.Normal.
        /// </summary>
        public static string TimeNormal {
            get {
                return ResourceManager.GetString("TimeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.Time.Normal.Diff.
        /// </summary>
        public static string TimeNormalDiff {
            get {
                return ResourceManager.GetString("TimeNormalDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Период нормальной работы {0} ч{1}.
        /// </summary>
        public static string TimeNormalPeriod {
            get {
                return ResourceManager.GetString("TimeNormalPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V{0}_{1}.
        /// </summary>
        public static string V {
            get {
                return ResourceManager.GetString("V", resourceCulture);
            }
        }
    }
}
