/*------------------------------------------------------------------------------
*<auto-generated>
*     This code was generated by a tool DeploymentSupport.linq.
*</auto-generated>
*------------------------------------------------------------------------------*/


SET IDENTITY_INSERT [Business].[Mnemoscheme] ON;


:setvar xmlQuote "'"
DECLARE @A230_1a NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Ecl310\A230.1a.svg
$(xmlQuote)

DECLARE @A230_1b NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Ecl310\A230.1b.svg
$(xmlQuote)

DECLARE @A230_1c NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Ecl310\A230.1c.svg
$(xmlQuote)

DECLARE @A230_1d NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Ecl310\A230.1d.svg
$(xmlQuote)

DECLARE @A230_2b NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Ecl310\A230.2b.svg
$(xmlQuote)

DECLARE @A230_2d NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Ecl310\A230.2d.svg
$(xmlQuote)

DECLARE @A230_2с NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Ecl310\A230.2с.svg
$(xmlQuote)

DECLARE @A231_1 NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Ecl310\A231.1.svg
$(xmlQuote)

DECLARE @A231_2 NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Ecl310\A231.2.svg
$(xmlQuote)

DECLARE @A260_1b NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Ecl310\A260.1b.svg
$(xmlQuote)

DECLARE @A260_1c NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Ecl310\A260.1c.svg
$(xmlQuote)

DECLARE @A260_1d NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Ecl310\A260.1d.svg
$(xmlQuote)

DECLARE @A260_1e NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Ecl310\A260.1e.svg
$(xmlQuote)

DECLARE @A260_1f NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Ecl310\A260.1f.svg
$(xmlQuote)

DECLARE @A266_1a NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Ecl310\A266.1a.svg
$(xmlQuote)

DECLARE @A266_1b NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Ecl310\A266.1b.svg
$(xmlQuote)

DECLARE @A266_2 NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Ecl310\A266.2.svg
$(xmlQuote)

DECLARE @A266_9 NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Ecl310\A266.9.svg
$(xmlQuote)

DECLARE @A331_1 NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Ecl310\A331.1.svg
$(xmlQuote)

DECLARE @A331_2 NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Ecl310\A331.2.svg
$(xmlQuote)

DECLARE @A361_1 NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Ecl310\A361.1.svg
$(xmlQuote)

DECLARE @A361_2 NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Ecl310\A361.2.svg
$(xmlQuote)

DECLARE @A368_1 NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Ecl310\A368.1.svg
$(xmlQuote)

DECLARE @A368_2 NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Ecl310\A368.2.svg
$(xmlQuote)

DECLARE @A368_3 NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Ecl310\A368.3.svg
$(xmlQuote)

DECLARE @A368_4 NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Ecl310\A368.4.svg
$(xmlQuote)

DECLARE @A368_6 NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Ecl310\ECL310_A368_6.svg
$(xmlQuote)

DECLARE @Vkt7Hws NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Vkt7\Vkt7Hws.svg
$(xmlQuote)

DECLARE @Vkt7Hwsco NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Vkt7\Vkt7Hwsco.svg
$(xmlQuote)

DECLARE @Vkt7CwsPipe1 NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Vkt7\Vkt7CwsPipe1.svg
$(xmlQuote)

DECLARE @Vkt7CwsPipe2 NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Vkt7\Vkt7CwsPipe2.svg
$(xmlQuote)

DECLARE @Vkt7HeatSys NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Vkt7\Vkt7HeatSys.svg
$(xmlQuote)

DECLARE @Vkt7CwsPipe3 NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Vkt7\Vkt7CwsPipe3.svg
$(xmlQuote)


DECLARE @Vkt7HwsSupply NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Vkt7\Vkt7HwsSupply.svg
$(xmlQuote)


DECLARE @Km5HeatSys NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Km5\Km5HeatSys.svg
$(xmlQuote)

DECLARE @Km5Hws NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Km5\Km5Hws.svg
$(xmlQuote)

DECLARE @Km5HwsSupply NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Km5\Km5HwsSupply.svg
$(xmlQuote)

DECLARE @Km5HwsReturn NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Km5\Km5HwsReturn.svg
$(xmlQuote)

DECLARE @Km5CwsSupply NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Km5\Km5CwsSupply.svg
$(xmlQuote)

DECLARE @Rm5CwsSupply NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Km5\Rm5CwsSupply.svg
$(xmlQuote)

DECLARE @Km5CwsReturn NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Km5\Km5CwsReturn.svg
$(xmlQuote)

DECLARE @Km5CwsImpulse NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Km5\Km5CwsImpulse.svg
$(xmlQuote)

DECLARE @Empty NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Common\Empty.svg
$(xmlQuote)

DECLARE @Km5Hwsco NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Km5\Km5Hwsco.svg
$(xmlQuote)

DECLARE @Ecl300_C66 NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Ecl300\C66.svg
$(xmlQuote)

DECLARE @boilerRoomGeneric1 NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\BoilerRoom\Generic2.svg
$(xmlQuote)

DECLARE @boilerRoomGeneric2 NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\BoilerRoom\Generic3.svg
$(xmlQuote)

DECLARE @typicalElectricityMeter NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Common\TypicalElectricityMeter.svg
$(xmlQuote)

DECLARE @closedHeatSys NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Common\ClosedHeatSys.svg
$(xmlQuote)

DECLARE @pulsar2Panel NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Pulsar\Pulsar2Panel.svg
$(xmlQuote)

DECLARE @pulsarPanelForGas NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Pulsar\PulsarPanelForGas.svg
$(xmlQuote)

DECLARE @tverCrystal46 NVARCHAR(MAX) = 
$(xmlQuote)
:r ..\_Svg\BoilerRoom\TverCrystal46.svg
$(xmlQuote)

DECLARE @almetKvartalBoilerRoom14 NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\BoilerRoom\AlmetKvartalBoilerRoom14.svg
$(xmlQuote)

DECLARE @almetKvartalBoilerRoom5 NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\BoilerRoom\AlmetKvartalBoilerRoom5.svg
$(xmlQuote)

DECLARE @almetKvartalBoilerRoom27 NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\BoilerRoom\AlmetKvartalBoilerRoom27.svg
$(xmlQuote)

DECLARE @almetKvartalBoilerRoom6 NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\BoilerRoom\AlmetKvartalBoilerRoom6.svg
$(xmlQuote)

DECLARE @carevoBoilerRoom NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\BoilerRoom\CarevoBoilerRoom.svg
$(xmlQuote)

DECLARE @vesnaBoilerRoom NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\BoilerRoom\VesnaBoilerRoom.svg
$(xmlQuote)

DECLARE @carevoColdWaterPressureMonitor NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\BoilerRoom\CarevoColdWaterPressureMonitor.svg
$(xmlQuote)

DECLARE @artCityBoilerRoom NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\BoilerRoom\ArtCityBoilerRoom.svg
$(xmlQuote)

DECLARE @mirasBoilerRoom NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\BoilerRoom\MirasBoilerRoom.svg
$(xmlQuote)

DECLARE @danfoss_mcx2 NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Ecl310\DanfossMCX2.svg
$(xmlQuote)

DECLARE @ecl310_a217_3 NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Ecl310\ECL310_A217_3.svg
$(xmlQuote)

DECLARE @ecl110_130 NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Ecl310\ECL110_130.svg
$(xmlQuote)

DECLARE @heatSysWithMassFlow NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\HeatSysWithMassFlow.svg
$(xmlQuote)

DECLARE @cwsForHwsWithMassFlow NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\CwsForHwsWithMassFlow.svg
$(xmlQuote)

DECLARE @ecl310_a260_1 NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Ecl310\ECL310_A260_1.svg
$(xmlQuote)

DECLARE @artCityErshova62G NVARCHAR(MAX) = 
$(xmlQuote)
:r ..\_Svg\ArtCity\Ershova62G.svg
$(xmlQuote)

DECLARE @vegaCI11_CWS NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Vega\CI11_CWS.svg
$(xmlQuote)

DECLARE @vegaCI11_HWS NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Vega\CI11_HWS.svg
$(xmlQuote)

DECLARE @hotWaterMeter NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\HotWaterMeter.svg
$(xmlQuote)

DECLARE @coldWaterMeter NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\ColdWaterMeter.svg
$(xmlQuote)

DECLARE @artCityErshova62D NVARCHAR(MAX) = 
$(xmlQuote)
:r ..\_Svg\ArtCity\Ershova62D.svg
$(xmlQuote)

DECLARE @artCityErshova62B NVARCHAR(MAX) = 
$(xmlQuote)
:r ..\_Svg\ArtCity\Ershova62B.svg
$(xmlQuote)

DECLARE @akhmerova5 NVARCHAR(MAX) = 
$(xmlQuote)
:r ..\_Svg\ArtCity\Akhmerova5.svg
$(xmlQuote)

DECLARE @akhmetzyanova10 NVARCHAR(MAX) = 
$(xmlQuote)
:r ..\_Svg\ArtCity\Akhmetzyanova10.svg
$(xmlQuote)

DECLARE @vkt7HeatSysScheme4WithoutPressureSensors NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Vkt7\Vkt7HeatSysScheme4WithoutPressureSensors.svg
$(xmlQuote)

DECLARE @vkt7HeatSysScheme4WithPressureSensors NVARCHAR(MAX) =
$(xmlQuote)
:r ..\_Svg\Vkt7\Vkt7HeatSysScheme4WithPressureSensors.svg
$(xmlQuote)



INSERT INTO [Business].[Mnemoscheme] ([Id], [MnemoschemeTypeId], [Description], [Image], [Zoom])
VALUES
(1, 1, 'Ключ A230.1a Независимое подключение системы отопления (обычно при централизованном теплоснабжении)', @A230_1a, 1),
(2, 1, 'Ключ A230.1b Зависимое подключение системы отопления', @A230_1b, 1),
(3, 1, 'Ключ A230.1c Система отопления с котлом и 3-х ходовым клапаном', @A230_1c, 1),
(4, 1, 'Ключ A230.1d Система отопления с котлом и 4-х ходовым клапаном', @A230_1d, 1),
(5, 1, 'Ключ A230.2b Зависимое присоединение системы охлаждения', @A230_2b, 1),
(6, 1, 'Ключ A230.2d Управление спаренными циркуляционными насосами', @A230_2d, 1),
(7, 1, 'Ключ A230.2c Независимое подключение системы охлаждения, постоянный поток на стороне подачи охлаждения', @A230_2с, 1),
(8, 1, 'Ключ A231.1 Независимое присоединение системы отопления с управлением двумя насосами и функцией подпитки', @A231_1, 1),
(9, 1, 'Ключ A231.2 Независимое присоединение системы отопления с управлением двумя насосами и функцией подпитки (измерение температуры первичного контура предоставляет дополнительные возможности по управленияю / ограничению', @A231_2, 1),
(10, 1, 'Ключ A260.1b Независимое присоединение систем отопления (обычно при централизованном теплоснабжении)', @A260_1b, 1),
(11, 1, 'Ключ A260.1c Зависимое присоединение систем отопления (обычно при централизованном теплоснабжении)', @A260_1c, 1),
(12, 1, 'Ключ A260.1d Независимое присоединение систем отопления (обычно при централизованном теплоснабжении). Контур 2 - напольное отопление', @A260_1d, 1),
(13, 1, 'Ключ A260.1e Зависимое присоединение систем отопления (с котлом). Контур 2 - напольное отопление', @A260_1e, 1),
(14, 1, 'Ключ A260.1f Зависимое присоединение систем отопления (с котлом)', @A260_1f, 1),
(16, 1, 'Ключ A266.1a Независимое присоединение системы отопления и ГВС (обычно при централизованном теплоснабжении)', @A266_1a, 1),
(17, 1, 'Ключ A266.1b Зависимое присоединение системы отопления и независимое присоединение системы ГВС', @A266_1b, 1),
(18, 1, 'Ключ A266.2 Независимое присоединение системы отопления и ГВС с датчиком потока', @A266_2, 1),
(19, 1, 'Ключ A266.9 Независимое присоединение системы отопления и ГВС с датчиком давления и универсальным датчиком сигнализации', @A266_9, 1),
(20, 1, 'Ключ A331.1 Независимое присоединение системы отопления с управлением двумя насосами и функцией подпитки', @A331_1, 1),
(21, 1, 'Ключ A331.2 Независимое присоединение системы отопления с управлением двумя насосами и функцией подпитки (измерение температуры первичного контура предоставляет дополнительные возможности по управлению / ограничению', @A331_2, 1),
(22, 1, 'Ключ A361.1 Независимое присоединение системы отопления с управлением двумя насосами и функцией подпитки', @A361_1, 1),
(23, 1, 'Ключ A361.2 Независимое присоединение системы отопления с управлением двумя насосами и функцией подпитки (измерение температуры первичного контура предоставляет дополнительные возможности по управлению / ограничению)', @A361_2, 1),
(24, 1, 'Ключ A368.1 Независимое присоединение системы отопления и ГВС с управлением двумя насосами и функцией подпитки', @A368_1, 1),
(25, 1, 'Ключ A368.2 Независимое присоединение системы отопления и ГВС с управлением двумя насосами и функцией подпитки (измерение температуры первичного контура предоставляет дополнительные возможности по управлению / ограничению)', @A368_2, 1),
(26, 1, 'Ключ A368.3 Независимое присоединение системы отопления и ГВС с управлением двумя насосами и функцией подпитки. Измерение давления в системе', @A368_3, 1),
(27, 1, 'Ключ A368.4 Независимое присоединение системы отопления и ГВС с управлением двумя насосами и функцией подпитки. Измерение температуры первичного контура обеспечивает дополнительные возможности по управлению / ограничению. Измерение давления в системе', @A368_4, 1),
(28, 1, 'ГВС с циркуляцией (закрытый водоразбор)', @Vkt7Hws, 1),
(29, 1, 'Учет объема (трубопровод 1)', @Vkt7CwsPipe1, 1),
(30, 1, 'Учет объема (трубопровод 2)', @Vkt7CwsPipe2, 1),
(31, 1, 'Открытая система отопления', @Vkt7HeatSys, 1),
(32, 1, 'Учет объема (трубопровод 3)', @Vkt7CwsPipe3, 1),
(34, 1, 'Тупиковая система ГВС (подающий трубопровод), дополнительный канал измерения расхода (Т3=1) или тепла (Т3=2) по тр3', @Vkt7HwsSupply, 1),
(35, 1, 'Тупиковая система ГВС (обратный трубопровод), дополнительный канал измерения расхода (Т3=1) или тепла (Т3=2) по тр3', @Empty, 1),

(38, 1, 'Открытая система отопления', @Km5HeatSys, 1),
(39, 1, 'Система горячего водоснабжения с циркуляцией (закрытый водоразбор)', @Km5Hws, 1),
(40, 1, 'Тупиковая система ГВС (подающий трубопровод)', @Km5HwsSupply, 1),
(41, 1, 'Тупиковая система ГВС (обратный трубопровод)', @Km5HwsReturn, 1),
(42, 1, 'Система холодного водоснабжения (подающий трубопровод)', @Km5CwsSupply, 1),
(43, 1, 'Система холодного водоснабжения (обратный трубопровод)', @Km5CwsReturn, 1),
(45, 1, 'Система холодного водоснабжения (импульсный вход)', @Km5CwsImpulse, 1),
(46, 1, 'Система холодного водоснабжения (подающий трубопровод)', @Rm5CwsSupply, 1),
(47, 1, 'ГВС с циркуляцией (открытый водоразбор)', @Vkt7Hwsco, 1),
(48, 1, 'Система горячего водоснабжения с циркуляцией (открытый водоразбор)', @Km5Hwsco, 1),
(49, 2, 'Типовая котельная с 5-ю котлами', @boilerRoomGeneric1, 1),
(50, 1, 'Независимое присоединение системы отопления и ГВС (обычно при централизованном теплоснабжении)', @Ecl300_C66, 1),

(52, 2, 'Типовая котельная с 4-мя котлами', @boilerRoomGeneric2, 1),
(53, 1, 'Типовой cчетчик электрической энергии электронный', @typicalElectricityMeter, 1),
(54, 1, 'Закрытая система отопления', @closedHeatSys, 1),
(55, 1, 'Cчетчик-импульсов Пульсар', @pulsar2Panel, 1),
(56, 2, 'ЦТП Хрустальная, 46 (г. Тверь)', @tverCrystal46, 1),
(57, 2, 'Квартальная котельная №14 (г. Альметьевск)', @almetKvartalBoilerRoom14, 1),
(58, 2, 'Квартальная котельная №5 (г. Альметьевск)', @almetKvartalBoilerRoom5, 1),
(59, 2, 'Квартальная котельная №27 (г. Альметьевск)', @almetKvartalBoilerRoom27, 1),
(60, 1, 'Cчетчик-импульсов Пульсар для учета газа', @pulsarPanelForGas, 1),
(61, 2, 'Котельная ЖК Царево Village', @carevoBoilerRoom, 1),
(62, 2, 'Котельная ЖК Весна', @vesnaBoilerRoom, 1),
(63, 2, 'Мониторинг давления холодной воды ЖК Царево Village', @carevoColdWaterPressureMonitor, 1),
(64, 1, 'Ключ A368.6 Регулирование отопления и ГВС. Регулирование насоса подпитки. Регулирование вторичной температуры', @A368_6, 1),
(65, 2, 'Котельная ЖК ART City', @artCityBoilerRoom, 1),
(66, 1, 'Danfoss MCX. Измерение температуры наружного воздуха, подачи и обратки', @danfoss_mcx2, 1),
(67, 1, 'Ключ A217.3 Система нагрева ГВС, независимое подключение. Циркуляция ГВС через теплообменник', @ecl310_a217_3, 1),
(68, 2, 'Котельная Мирас', @mirasBoilerRoom, 1),
(69, 1, 'Ключ 130. Система отопления', @ecl110_130, 1),
(70, 1, 'Открытая система отопления (массовый расход)', @heatSysWithMassFlow, 1),
(71, 1, 'Учет объема ХВС для ГВС (массовый расход)', @cwsForHwsWithMassFlow, 1),
(72, 1, 'Ключ A260.1. Независимое присоединение двух систем отопления', @ecl310_a260_1, 1),
(73, 2, 'ЖК АРТ СИТИ (Ершова, 62Г)', @artCityErshova62G, 1),
(74, 1, 'Счетчик-импульсов ВЕГА СИ-11 (холодная вода)', @vegaCI11_CWS, 1),
(75, 1, 'Счетчик-импульсов ВЕГА СИ-11 (горячая вода)', @vegaCI11_HWS, 1),
(76, 1, 'Обычный счетчик горячей воды', @hotWaterMeter, 1),
(77, 1, 'Обычный счетчик холодной воды', @coldWaterMeter, 1),
(78, 2, 'ЖК АРТ СИТИ (Ершова, 62Д)', @artCityErshova62D, 1),
(79, 2, 'ЖК АРТ СИТИ (Ершова, 62В)', @artCityErshova62B, 1),
(80, 2, 'ЖК АРТ СИТИ (Ахмерова, 5)', @akhmerova5, 1),
(81, 2, 'ЖК АРТ СИТИ (Ахметзянова, 10)', @akhmetzyanova10, 1),
(82, 1, 'Закрытая система отопления, измерение расхода в подающем трубопроводе (ВКТ7, СИ=4, без датчиков давления)', @vkt7HeatSysScheme4WithoutPressureSensors, 1),
(83, 1, 'Закрытая система отопления, измерение расхода в подающем трубопроводе (ВКТ7, СИ=4, с датчиками давления)', @vkt7HeatSysScheme4WithPressureSensors, 1),
(84, 2, 'Квартальная котельная №6 (г. Альметьевск)', @almetKvartalBoilerRoom6, 1)



--([Id], [MnemoschemeTypeId], [Description], [Image], [Zoom])

GO

SET IDENTITY_INSERT [Business].[Mnemoscheme] OFF;
